import localfont from "next/font/local";

import "./globals.css";
import { ThemeProvider } from "@/context/ThemeProvider";

const buzinga = localfont({
  src: "../public/fonts/Buzinga-Regular.otf",
  variable: "--font-buzinga",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ThemeProvider>
      <html lang="en">
        <body className={buzinga.variable}>{children}</body>
      </html>
    </ThemeProvider>
  );
}
